# Generated by Django 5.0 on 2024-03-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("TL", "Team Lead"),
                            ("PO", "Product Owner"),
                            ("PM", "Project Manager"),
                            ("OA", "Office Assistant"),
                            ("SWE", "Software Engineer"),
                            ("HRM", "Human Resource Manager"),
                            ("SQAE", "Software Quality Assurance Engineer"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TakenDeviceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        choices=[
                            ("mobile", "mobile"),
                            ("tab", "tab"),
                            ("laptop", "laptop"),
                        ],
                        max_length=100,
                    ),
                ),
                ("taken_date", models.DateTimeField(auto_now_add=True)),
                ("return_data", models.DateTimeField(auto_now=True)),
                (
                    "device_condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                            ("faulty", "Faulty"),
                            ("repaired", "Repaired"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.employee",
                    ),
                ),
            ],
        ),
    ]
