# Generated by Django 5.0 on 2024-03-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                choices=[("emma", "emma")],
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.company",
            ),
        ),
    ]
