# Generated by Django 5.0 on 2024-03-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0002_alter_company_name_alter_employee_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tab", "Tablet"),
                            ("laptop", "Laptop"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                            ("faulty", "Faulty"),
                            ("repaired", "Repaired"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.company"
            ),
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_date", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout_condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                            ("faulty", "Faulty"),
                            ("repaired", "Repaired"),
                        ],
                        max_length=100,
                    ),
                ),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                (
                    "return_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                            ("faulty", "Faulty"),
                            ("repaired", "Repaired"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.employee",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.device",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TakenDeviceHistory",
        ),
    ]
