# Generated by Django 5.0 on 2024-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.PositiveIntegerField()),
                ("job_location", models.CharField(max_length=100)),
                ("mobile", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("profile_photo", models.ImageField(blank=True, upload_to="images")),
                ("resume_file", models.FileField(blank=True, upload_to="documents")),
            ],
        ),
    ]
